// Permission enum for backend
export enum Permission {
  // User management
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  VIEW_USER = 'VIEW_USER',
  MANAGE_USER_ROLES = 'MANAGE_USER_ROLES',
  
  // Organization management
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',
  VIEW_ORGANIZATION = 'VIEW_ORGANIZATION',
  MANAGE_ORGANIZATION_SETTINGS = 'MANAGE_ORGANIZATION_SETTINGS',
  
  // Contact management
  CREATE_CONTACT = 'CREATE_CONTACT',
  UPDATE_CONTACT = 'UPDATE_CONTACT',
  DELETE_CONTACT = 'DELETE_CONTACT',
  VIEW_CONTACT = 'VIEW_CONTACT',
  BULK_CONTACT_OPERATIONS = 'BULK_CONTACT_OPERATIONS',
  EXPORT_CONTACTS = 'EXPORT_CONTACTS',
  
  // Campaign management
  CREATE_CAMPAIGN = 'CREATE_CAMPAIGN',
  UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN',
  DELETE_CAMPAIGN = 'DELETE_CAMPAIGN',
  VIEW_CAMPAIGN = 'VIEW_CAMPAIGN',
  SEND_CAMPAIGN = 'SEND_CAMPAIGN',
  SCHEDULE_CAMPAIGN = 'SCHEDULE_CAMPAIGN',
  
  // Task management
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_TASK = 'UPDATE_TASK',
  DELETE_TASK = 'DELETE_TASK',
  VIEW_TASK = 'VIEW_TASK',
  ASSIGN_TASK = 'ASSIGN_TASK',
  
  // Workflow management
  CREATE_WORKFLOW = 'CREATE_WORKFLOW',
  UPDATE_WORKFLOW = 'UPDATE_WORKFLOW',
  DELETE_WORKFLOW = 'DELETE_WORKFLOW',
  VIEW_WORKFLOW = 'VIEW_WORKFLOW',
  EXECUTE_WORKFLOW = 'EXECUTE_WORKFLOW',
  
  // AI operations
  USE_AI_FEATURES = 'USE_AI_FEATURES',
  EXECUTE_AI_TASKS = 'EXECUTE_AI_TASKS',
  APPROVE_AI_OPERATIONS = 'APPROVE_AI_OPERATIONS',
  CONFIGURE_AI_SETTINGS = 'CONFIGURE_AI_SETTINGS',
  
  // Data operations
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  EXPORT_DATA = 'EXPORT_DATA',
  IMPORT_DATA = 'IMPORT_DATA',
  DELETE_DATA = 'DELETE_DATA',
  MANAGE_REPORTS = 'MANAGE_REPORTS',
  VIEW_REPORTS = 'VIEW_REPORTS',
  GENERATE_REPORTS = 'GENERATE_REPORTS',
  MANAGE_ALERTS = 'MANAGE_ALERTS',
  
  // System administration
  MANAGE_INTEGRATIONS = 'MANAGE_INTEGRATIONS',
  MANAGE_BILLING = 'MANAGE_BILLING',
  VIEW_SYSTEM_LOGS = 'VIEW_SYSTEM_LOGS',
  MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS',
  VIEW_ADMIN = 'VIEW_ADMIN',
  
  // Security operations
  MANAGE_SECURITY_SETTINGS = 'MANAGE_SECURITY_SETTINGS',
  VIEW_SECURITY_LOGS = 'VIEW_SECURITY_LOGS',
  MANAGE_API_KEYS = 'MANAGE_API_KEYS',
  
  // Dashboard and notifications
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS'
}
